"""
Stage 11 -- draw the system and model architecture diagram.

The pipeline and the proposed model are described in prose in Chapter 5, but a
reader cannot check a data-flow claim against a paragraph. This script draws
both: the six-stage pipeline with the cached artefact passed between stages,
and the internal structure of Consistency-Gated Fusion including the gate and
the gradient-reversal branch.

The figure is drawn with matplotlib primitives rather than an external
diagramming tool so that it is regenerated by the same command as every other
figure and cannot drift from the code it documents.

    python -m src.fig_architecture
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt                                 # noqa: E402
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch   # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from src import config as C                                     # noqa: E402

INK = "#1F3864"
EDGE = "#8B9BB4"
FILL = "#EFF3F8"
ACCENT = "#C44E52"
GATE = "#DD8452"
MUTED = "#5A6B84"


def box(ax, x, y, w, h, text, fill=FILL, edge=EDGE, fs=7.0, weight="normal"):
    """Draw a rounded box with centred, vertically spaced label text."""
    ax.add_patch(FancyBboxPatch((x, y), w, h,
                                boxstyle="round,pad=0.012,rounding_size=0.02",
                                linewidth=0.9, edgecolor=edge, facecolor=fill))
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center",
            fontsize=fs, color=INK, weight=weight, linespacing=1.4)


def arrow(ax, xy_from, xy_to, colour=EDGE, dashed=False, lw=0.9):
    """Draw a single-headed connector between two points in axes coordinates."""
    ax.add_patch(FancyArrowPatch(
        xy_from, xy_to, arrowstyle="-|>", mutation_scale=8, linewidth=lw,
        color=colour, linestyle="--" if dashed else "-",
        shrinkA=1.5, shrinkB=1.5))


# --------------------------------------------------------------------------- #
def panel_pipeline(ax) -> None:
    """Panel (a): the staged pipeline and the artefact cached at each step."""
    ax.set_title("(a) Processing pipeline", fontsize=8.5, color=INK,
                 loc="left", pad=4)
    stages = [
        ("1", "Corpus build", "21,798 posts\nthree split columns"),
        ("2", "Frozen encoders", "CLIP, DistilRoBERTa\nconsistency scores"),
        ("3", "Language model", "hidden state\nzero-shot P(false)"),
        ("4", "Experiment grid", "21 systems, 3 protocols\n165 runs"),
        ("5", "Robustness", "ablation, behavioural\nprobe, cost"),
        ("6", "Analysis", "intervals, tests\nfigures, tables"),
    ]
    caches = ["corpus.parquet", "feat_base.npz", "feat_llm.npz",
              "runs.csv, preds/", "robustness.csv", "figures/, tables"]
    y, h, w, gap = 0.50, 0.42, 0.145, 0.0245
    for i, (num, name, detail) in enumerate(stages):
        x = 0.02 + i * (w + gap)
        box(ax, x, y, w, h, num + "  " + name + "\n\n" + detail, fs=6.0)
        if i:
            arrow(ax, (x - gap, y + h / 2), (x, y + h / 2))
        box(ax, x, y - 0.32, w, 0.21, caches[i], fill="#FFFFFF", fs=5.7)
        arrow(ax, (x + w / 2, y), (x + w / 2, y - 0.11), colour="#B7C2D4")
    ax.text(0.02, 0.02, "Each stage writes a cached artefact that the next "
                        "reads, so any stage can be re-run in isolation.",
            fontsize=6.1, color=MUTED, style="italic")


# --------------------------------------------------------------------------- #
def panel_cgf(ax) -> None:
    """Panel (b): Consistency-Gated Fusion, including the adversarial branch."""
    ax.set_title("(b) Consistency-Gated Fusion", fontsize=8.5, color=INK,
                 loc="left", pad=4)
    iw, ih = 0.185, 0.145
    box(ax, 0.015, 0.76, iw, ih, "headline\nDistilRoBERTa (768)", fs=6.1)
    box(ax, 0.015, 0.56, iw, ih, "image\nCLIP ViT-B/32 (512)", fs=6.1)
    box(ax, 0.015, 0.32, iw, ih, "consistency\ncosine, batch rank", fs=6.1)
    box(ax, 0.015, 0.12, iw, ih, "metadata\nnine features", fs=6.1)

    box(ax, 0.265, 0.76, 0.115, ih, "project\n256", fs=6.1)
    box(ax, 0.265, 0.56, 0.115, ih, "project\n256", fs=6.1)
    arrow(ax, (0.20, 0.833), (0.265, 0.833))
    arrow(ax, (0.20, 0.633), (0.265, 0.633))

    box(ax, 0.455, 0.76, 0.165, ih,
        "interaction\n$t \\odot v$,   $|t - v|$", fs=6.1)
    arrow(ax, (0.38, 0.833), (0.455, 0.833))

    box(ax, 0.455, 0.56, 0.165, ih,
        "consistency gate\n$\\sigma(\\cdot)$",
        fill="#FBEDE3", edge=GATE, fs=6.4, weight="bold")
    arrow(ax, (0.38, 0.633), (0.455, 0.633))
    arrow(ax, (0.20, 0.41), (0.50, 0.555), colour=GATE, dashed=True)

    box(ax, 0.675, 0.45, 0.125, 0.46, "concat\n\nfused\nrepresentation",
        fs=6.1)
    arrow(ax, (0.62, 0.833), (0.675, 0.82))
    arrow(ax, (0.62, 0.633), (0.675, 0.68))
    arrow(ax, (0.20, 0.393), (0.675, 0.56))
    arrow(ax, (0.20, 0.193), (0.675, 0.49))

    box(ax, 0.855, 0.71, 0.135, ih, "classifier\nP(false)", fs=6.3,
        weight="bold")
    arrow(ax, (0.80, 0.78), (0.855, 0.78))

    box(ax, 0.855, 0.27, 0.135, 0.20,
        "gradient reversal\n\nsource-community\nadversary",
        fill="#FFFFFF", edge=ACCENT, fs=5.9)
    arrow(ax, (0.80, 0.52), (0.855, 0.42), colour=ACCENT, dashed=True)

    ax.text(0.015, 0.03,
            "Dashed orange: the consistency scores also drive the gate, which "
            "rescales the visual stream element-wise.  Dashed red: the "
            "adversarial variant only.\nThe gate is a bounded per-item "
            "quantity and is therefore readable at inference.",
            fontsize=6.0, color=MUTED, style="italic", linespacing=1.5)


# --------------------------------------------------------------------------- #
def main() -> None:
    fig, axes = plt.subplots(2, 1, figsize=(7.4, 5.4),
                             gridspec_kw={"height_ratios": [1, 1.5]})
    panel_pipeline(axes[0])
    panel_cgf(axes[1])
    # Limits are fixed after drawing: adding a patch re-enables autoscaling,
    # so setting them first would let the last box drawn crop the panel.
    for ax, top in zip(axes, (0.99, 1.01)):
        ax.set_xlim(-0.02, 1.035)
        ax.set_ylim(-0.02, top)
        ax.axis("off")
    fig.subplots_adjust(left=0.01, right=0.99, top=0.94,
                        bottom=0.02, hspace=0.30)
    out = C.FIGURES / "fig0_architecture.png"
    fig.savefig(out, dpi=200, facecolor="white")
    plt.close(fig)
    print(f"[arch] wrote {out}")


if __name__ == "__main__":
    main()
