"""
Stage 8 -- render the report's tables directly from the results files.

The results tables in Chapter 6 are generated by this script rather than
transcribed by hand, so a number in the report cannot drift from the number in
``results/``. Re-running it after any change to the experiments regenerates the
tables verbatim.

    python -m src.make_tables > docs/tables.md
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from src import config as C                                     # noqa: E402
from src.analyse import PRETTY                                  # noqa: E402

pd.set_option("display.width", 200)


def md(df: pd.DataFrame) -> str:
    return df.to_markdown(index=False)


def main() -> None:
    ci = pd.read_csv(C.RESULTS / "confidence_intervals.csv")
    summ = pd.read_csv(C.RESULTS / "summary.csv")
    sig = pd.read_csv(C.RESULTS / "significance.csv")

    order = ["majority", "subreddit_probe", "llm_zeroshot", "tfidf_lr",
             "meta", "cons", "image", "text", "llm_emb", "late", "concat",
             "concat_meta", "cgf", "cgf_adv", "cgf_llm", "cgf_llm_adv"]
    abl = ["cgf", "cgf_no_gate", "cgf_no_cons", "cgf_no_inter", "cgf_no_meta"]

    # ---- Table: headline results per protocol ---------------------------- #
    for proto in ["random", "source", "temporal"]:
        sub = ci[(ci.protocol == proto) & (ci.model.isin(order))].copy()
        sub["Model"] = sub["model"].map(lambda m: PRETTY.get(m, m))
        sub["rank"] = sub["model"].map(lambda m: order.index(m))
        sd = (summ[summ.protocol == proto]
              .set_index("model")["macro_f1_std"].to_dict())
        sub["macro-F1 (95% CI)"] = [
            f"{r.macro_f1:.3f} [{r.macro_f1_lo:.3f}, {r.macro_f1_hi:.3f}]"
            for r in sub.itertuples()]
        sub["sd(seeds)"] = sub["model"].map(
            lambda m: f"{sd.get(m, float('nan')):.3f}"
            if pd.notna(sd.get(m, np.nan)) else "-")
        out = (sub.sort_values("rank")[["Model", "accuracy",
                                        "macro-F1 (95% CI)", "sd(seeds)",
                                        "auroc", "recall_fake", "ece"]]
               .round(3))
        out.columns = ["Model", "Acc", "macro-F1 (95% CI)", "sd", "AUROC",
                       "Recall(fake)", "ECE"]
        print(f"\n### Results, {proto} split\n")
        print(md(out))

    # ---- Table: protocol gap --------------------------------------------- #
    piv = (ci[ci.model.isin(order)]
           .pivot(index="model", columns="protocol", values="macro_f1"))
    if {"random", "source"} <= set(piv.columns):
        piv["drop (random - source)"] = piv["random"] - piv["source"]
    piv = piv.reindex([m for m in order if m in piv.index]).round(3)
    piv.index = [PRETTY.get(m, m) for m in piv.index]
    print("\n### Protocol gap (macro-F1)\n")
    print(piv.to_markdown())

    # ---- Table: ablation -------------------------------------------------- #
    a = (ci[ci.model.isin(abl)]
         .pivot(index="model", columns="protocol", values="macro_f1"))
    a = a.reindex([m for m in abl if m in a.index]).round(3)
    a.index = [PRETTY.get(m, m) for m in a.index]
    print("\n### Ablation (macro-F1)\n")
    print(a.to_markdown())

    # ---- Table: significance vs reference --------------------------------- #
    for proto in ["source", "random"]:
        s = sig[sig.protocol == proto].copy()
        if s.empty:
            continue
        s["Model"] = s["model"].map(lambda m: PRETTY.get(m, m))
        s["Δ macro-F1 [95% CI]"] = [
            f"{r.delta_mean:+.3f} [{r.delta_lo:+.3f}, {r.delta_hi:+.3f}]"
            for r in s.itertuples()]
        s["McNemar p"] = s["p_value"].map(
            lambda v: "<0.001" if v < 1e-3 else f"{v:.3f}")
        print(f"\n### Significance vs {s['reference'].iloc[0]}, {proto} split\n")
        print(md(s[["Model", "Δ macro-F1 [95% CI]", "McNemar p"]]))

    # ---- Robustness and behavioural --------------------------------------- #
    rp = C.RESULTS / "robustness.csv"
    if rp.exists():
        r = pd.read_csv(rp)
        t = (r.groupby(["protocol", "model", "condition"])["macro_f1"]
             .mean().unstack("condition").round(3))
        print("\n### Robustness (macro-F1 by test-time condition)\n")
        print(t.to_markdown())
    bp = C.RESULTS / "behavioural.csv"
    if bp.exists():
        b = pd.read_csv(bp)
        t = (b.groupby(["protocol", "model"])
             [["mean_p_fake_clean_true", "mean_p_fake_shuffled_true",
               "delta_p_fake_true", "flip_rate_true"]].mean().round(3))
        print("\n### Behavioural probe: image shuffled, headline kept\n")
        print(t.to_markdown())

    cp = C.RESULTS / "inference_cost.json"
    if cp.exists():
        print("\n### Measured inference cost (ms per item, 2-core CPU)\n")
        print(json.dumps(json.loads(cp.read_text()), indent=2))

    ft = C.RESULTS / "runs_finetuned.csv"
    if ft.exists():
        f = pd.read_csv(ft)
        print("\n### End-to-end fine-tuned text baseline\n")
        print(md(f[["protocol", "model", "accuracy", "macro_f1",
                    "auroc"]].round(3)))


if __name__ == "__main__":
    main()
